management:
  context-path: /manage

server:
  context-path: /uaa
security:
  user:
    name: username
    password: password
  ignored:
    - /css/**
    - /js/**
    - /favicon.ico
    - /webjars/**
logging:
  level:
    org.springframework.security: DEBUG
spring:
  redis:
    database: 0
    host: localhost
    password: password
    port: 6379
    timeout: 1000
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
  datasource:
    data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/auth-server?useUnicode=true&characterEncoding=utf8
    name:
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show_sql: true
    generate-ddl: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
